replicaCount: 1

image:
  tag:        "latest"
  repo:       "thevivek2"
  imageName:  "demo-matrix"
  pullPolicy: "IfNotPresent"

service:
  name: matix-demo
  type: ClusterIP
  internalPort: 8080
  externalPort: 80

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
